### ISSUE TITLE
Detection

### ISSUE THREAD

**Issue by sadfaceissad** [FilipeSilvens/aquaExternal#2]
Is this safe to run with VAC or not ?

**Comment by FilipeSilvens** [comment]
I don't use this but I'm pretty sure externals are safe from VAC detections on Linux, just make sure you run the cheat as root.

**Comment by sadfaceissad** [comment]
Oh there's an internal linux hack that isn't detected ? AFAIK, Aimtux and all the other forks got detected as the .load method got busted. May I ask what you're using ?

**Comment by FilipeSilvens** [comment]
using a private fork
the issue tracker is not for conversations, closed.
